### ISSUE TITLE
node 16.0.0 环境下，使用npm安装时发生错误

### ISSUE THREAD

**Issue by soonboylena** [foxpage/foxpage-cli#1]
环境：
  linux (manjaro-i3wm)
  node: 16.0.0

执行命令：
`npm install @foxpage/foxpage-cli -g`

![image](https://user-images.githubusercontent.com/16619932/166148664-fa6b4e03-c37a-43ca-93c8-bafc85b4970d.png)

错误详细日志：
[2022-05-01T13_35_11_067Z-debug.log](https://github.com/foxpage/foxpage-cli/files/8599039/2022-05-01T13_35_11_067Z-debug.log)

补充：现在将node版本由16.0.0 改成14.15.1， 安装成功。

**Comment by melodyJie** [comment]
最新版本^0.3.2 已兼容 node16 环境
